export const AUDIT_ACTIONS = {
  IDEA_CREATED: 'IDEA_CREATED',
  IDEA_UPDATED: 'IDEA_UPDATED',
  IDEA_PUBLISHED: 'IDEA_PUBLISHED',
  IDEA_UNPUBLISHED: 'IDEA_UNPUBLISHED',
  IDEA_ARCHIVED: 'IDEA_ARCHIVED',
  IDEA_RESTORED: 'IDEA_RESTORED',
  IDEA_IMAGE_ADDED: 'IDEA_IMAGE_ADDED',
  IDEA_IMAGE_REPLACED: 'IDEA_IMAGE_REPLACED',
  IDEA_IMAGE_REMOVED: 'IDEA_IMAGE_REMOVED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  DISTRICT_CREATED: 'DISTRICT_CREATED',
  DISTRICT_UPDATED: 'DISTRICT_UPDATED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  NEWS_CREATED: 'NEWS_CREATED',
  NEWS_UPDATED: 'NEWS_UPDATED',
  NEWS_PUBLISHED: 'NEWS_PUBLISHED',
  NEWS_UNPUBLISHED: 'NEWS_UNPUBLISHED',
  NEWS_IMAGE_ADDED: 'NEWS_IMAGE_ADDED',
  NEWS_IMAGE_REPLACED: 'NEWS_IMAGE_REPLACED',
  NEWS_IMAGE_REMOVED: 'NEWS_IMAGE_REMOVED',
  VOTE_EXCLUDED: 'VOTE_EXCLUDED',
  VOTE_RESTORED: 'VOTE_RESTORED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ENTITIES = {
  IDEA: 'IDEA',
  CATEGORY: 'CATEGORY',
  DISTRICT: 'DISTRICT',
  SETTINGS: 'SETTINGS',
  NEWS: 'NEWS',
  VOTE: 'VOTE',
} as const;

export const SETTINGS_ENTITY_ID = 'publicity';
export const SETTINGS_OBJECT_LABEL = 'Настройки публичности';

export type AuditEntityType =
  (typeof AUDIT_ENTITIES)[keyof typeof AUDIT_ENTITIES];

export const DEFAULT_AUDIT_PAGE = 1;
export const DEFAULT_AUDIT_PAGE_SIZE = 100;
export const MAX_AUDIT_PAGE_SIZE = 100;
